version: "2.0"
services:
  "tws":
    image: ib-tws
    build: .
    stdin_open: true
    tty: true
    privileged: true
    security_opt:
      - seccomp:"./chrome.json"
    devices:
      - "/dev/snd/:/dev/snd/"
    ipc: host
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - "./data:/home/tws/data:rw"
      - "./.mozilla:/home/tws/.mozilla:rw"
      - "./Jts:/home/tws/Jts:rw"
      - "/tmp/.X11-unix/:/tmp/.X11-unix/:ro"
      - "~/.Xauthority:/home/tws/.Xauthority:rw"
      - "/var/lib/usbmux:/var/lib/usbmux"
      - "/var/run/user/1000/pulse:/run/user/1000/pulse"
      - "/etc/asound.conf:/etc/asound.conf"
