version: "2.0"
services:
  "tws":
    image: ib-tws
    build: .
    stdin_open: true
    tty: true
    privileged: true
    security_opt:
      - seccomp:"./chrome.json"
    devices:
      - "/dev/snd/:/dev/snd/"
    ipc: host
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - "/tmp/.X11-unix/:/tmp/.X11-unix/:ro"
      - "~/.Xauthority:/home/tws/.Xauthority:rw"
      - "/etc/asound.conf:/etc/asound.conf"
